export enum ValidateProfileErrors {
    INCORRECT_USER_DATA = 'PROFILE_EDIT_INCORRECT_USER_DATA',
    INCORRECT_USER_AGE = 'PROFILE_EDIT_INCORRECT_USER_AGE',
    INCORRECT_USER_COUNTRY = 'PROFILE_EDIT_INCORRECT_USER_COUNTRY',
    INCORRECT_USERNAME = 'PROFILE_EDIT_INCORRECT_USERNAME',
    NO_DATA = 'PROFILE_EDIT_NO_DATA',
    SERVER_ERROR = 'SERVER_ERROR',
}
