export { GameHeader } from './ui/GameHeader/GameHeader'
export { GameFooter } from './ui/GameFooter/GameFooter'
export { GameContent as MultiplayerGameContent } from './ui/GameMultiplayer/GameContent/GameContent'
export { GameContent as SingleGameContent } from './ui/GameSingle/GameContent/GameContent'
export { useObservable } from './lib/SingleGameCore/hooks/useObservable'
export { GameMode, gameService, GameStatus } from './lib/services/gameService'
export { GameRateModal } from './ui/GameRateModal/GameRateModal'
