export enum ValidateRegistrationErrors {
    INCORRECT_USERNAME = 'INCORRECT_USERNAME',
    SERVER_ERROR = 'SERVER_ERROR',
    SERVER_ERROR_USERNAME_REQUIRED = 'SERVER_ERROR_USERNAME_REQUIRED',
    SERVER_ERROR_USERNAME_EXISTS = 'SERVER_ERROR_USERNAME_EXISTS',
    SERVER_ERROR_PASSWORD_REQUIRED = 'SERVER_ERROR_PASSWORD_REQUIRED',
}
