export type { ProfileSchema, Profile } from './model/types/profile'
export { getProfileData } from './model/selectors/getProfileData/getProfileData'
export { getProfileError } from './model/selectors/getProfileError/getProfileError'
export { getProfileIsLoading } from './model/selectors/getProfileIsLoading/getProfileIsLoading'
export { profileActions, profileReducer } from './model/slices/profileSlice'
export { fetchProfileData } from './model/services/fetchProfileData/fetchProfileData'
