name: BUILD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: user/app:latest


      - name: "Build and push: nginx"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .deploy/nginx.Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/bomberman-nginx:${{env.VERSION}}

      - name: Image list
        run: docker image list

    # - name: Pull images
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       docker pull ghcr.io/vicpril/bomberman-sockets:${{env.VERSION}}
    #       docker pull ghcr.io/vicpril/bomberman-frontend:${{env.VERSION}}
    #       docker pull ghcr.io/vicpril/bomberman-api:${{env.VERSION}}
    #       docker pull ghcr.io/vicpril/bomberman-json:${{env.VERSION}}
    #       docker pull ghcr.io/vicpril/bomberman-nginx:${{env.VERSION}}
    #       docker image list

    # - name: 'Refresh .env: copy template to remote'
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     source: ".env.production,.deploy/docker-compose.yml"
    #     target: /home/${{ secrets.SSH_USER }}
    #     overwrite: true
    #     strip_components: 1
        
    # - name: 'Refresh .env: edit .env with secrets'
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       cd /home/${{ secrets.SSH_USER }}/
    #       rm -f .env
    #       mv .env.production .env
    #       printf "\nPOSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
    #       printf "\nPGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> .env

    # - name: Reload remote components
    #   uses: appleboy/ssh-action@v1.0.3
    #   with: 
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       cd /home/${{ secrets.SSH_USER }}/
    #       docker-compose down
    #       docker-compose up -d --build --force-recreate
